name: Fetch GitHub Stats

on:
  schedule:
    - cron: "0 0,12 * * *" # Runs automatically twice a day
  workflow_dispatch: # Gives you a button to trigger it manually

jobs:
  update-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grants the bot permission to push to your repo

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Main Stats
        run: 'curl -f -H "User-Agent: Mozilla/5.0" -o github-stats.svg "https://github-readme-stats.vercel.app/api?username=Alpha241026&show_icons=true&theme=tokyonight&hide_border=true"'

      - name: Download Streak Stats
        run: 'curl -f -H "User-Agent: Mozilla/5.0" -o github-streak.svg "https://streak-stats.demolab.com/?user=Alpha241026&theme=tokyonight&hide_border=true"'
          
      - name: Commit and Push Images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-update github stats"
          file_pattern: "*.svg"
